### ISSUE TITLE
Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by paq85** [jaryn-kubik/AcerFanControl#1]
Hi @jaryn-kubik 
1. Were you able to run in on Windows 10 with Anniversary Update?
2. Could you make a release with the latest version so I can download the "exe" file?

I was using your tool with success but it seems it stopped working after I've installed the Anniversary Update.

Thank you for such a useful software! :)

**Comment by kubik-jaroslav** [comment]
Only noticed this now, way too late I assume, sorry... For some reason there are no notifications anywhere for open issues on your repos.
The Anniversary Update removes the drivers necessary for this app to work, so you just simply need to [reinstall them](https://raw.githubusercontent.com/jaryn-kubik/AcerFanControl/master/drivers.zip) and it should continue to work (at least for me that was the only thing I had to do to make it work again). I'm guessing you probably figured that out by now though.

**Comment by paq85** [comment]
Hi @jaryn-kubik ,  no problem. 
I've figured that out and it works :)

Thanks.
