### ISSUE TITLE
How to run this ?

### ISSUE THREAD

**Issue by Daszek** [jaryn-kubik/AcerFanControl#3]
Hello, I am trying to get rid of this annoying problem with Acer 5750G fan. I am new a GitHub. Can you tell me how to run your program in few words ?

**Comment by kubik-jaroslav** [comment]
1. [Install the drivers provided by Acer](https://raw.githubusercontent.com/jaryn-kubik/AcerFanControl/master/drivers.zip)
2. [Download the latest release](https://github.com/jaryn-kubik/AcerFanControl/releases/latest)
3. Unzip it somewhere and start it up.

There's not much more to it, there are two sliders - one controls the temperature at which it turns the fan to the max, other one controls the time after it will tone the fan back down.

I updated the readme with this.
