### ISSUE TITLE
Invalid device handler

### ISSUE THREAD

**Issue by Boryz** [jaryn-kubik/AcerFanControl#4]
invalid device handler while sldier value changed. 
Acer V3-571G

**Comment by kubik-jaroslav** [comment]
"Invalid device handler" = it can't find the driver. Try reinstalling it (https://raw.githubusercontent.com/jaryn-kubik/AcerFanControl/master/drivers.zip, run common.exe, restart your pc after that). Windows updates like the Creators Update tend to uninstall it for some reason, so if you recently upgraded, this is probably it.

**Comment by belgareth** [comment]
It doesn't seem to work for Acer 5750g.

**Comment by NEONZARIN** [comment]
After installing windows 10 I also had this problem "Invalid device handler". It helped remove (reload windows) and reinstall (reload windows) of the FanControl / master / drivers.zip driver. On windows 7, this problem is not noticed. Laptop Acer 5750ZG, Windows 10 x64 Enterprise build 16299.

**Comment by kubik-jaroslav** [comment]
same as all the other "Invalid device handle" problems, the semi-annual Windows updates remove the drivers for some reason... updated the readme with the solution
