### ISSUE TITLE
DLL not found, but in directory

### ISSUE THREAD

**Issue by Root-Core** [jaryn-kubik/AcerFanControl#5]
Hello,

i just ran the tool, but it throws errors while switching the "State"-slider.

```
---------------------------

---------------------------
System.DllNotFoundException: Die DLL "AcerFanControlLib.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.

   bei AcerFanControl.AcerFanControlLib.off()

   bei AcerFanControl.MainWindow.mainSlider_ValueChanged(Object sender, RoutedPropertyChangedEventArgs`1 e)
---------------------------
OK   
---------------------------
```

The file is in place (running `dir` and in the explorer):

```
08.12.2016  23:57            30.208 AcerFanControl.exe
19.08.2017  05:05            14.544 AcerFanControl.sys
08.12.2016  23:57            10.752 AcerFanControlLib.dll
```

I even tried to run the tool via shortcut, with the "running in" set to the correct path.
It does not work at all.

**Comment by kubik-jaroslav** [comment]
> running `dir`

What you copied is the full output or did you just copy out a part? Because you're also supposed to have `OpenHardwareMonitorLib.dll` in there, so maybe that got eaten by some antivirus or whatever.

Also it might need https://www.microsoft.com/en-us/download/details.aspx?id=48145 installed if you don't have it. Or I just reuploaded the last release with a version that doesn't need this dependency, so you could try that.

**Comment by Root-Core** [comment]
Yes, `OpenHardwareMonitorLib.dll` is in place.
Sorry about that.

VCRedist is installed ofc. This should be default with  Win10, i think.
But this won't help here. :(

**Comment by kubik-jaroslav** [comment]
Then I'm sorry but I got no idea what else could it be. The error makes no sense, it's a simple `DllImport`, .NET/Windows should handle finding it if it's in the same directory.

**Comment by Root-Core** [comment]
An update to Win10 creators update has fixed it for me.
But the tool has to run a little while to not get an invalid handle error, when triggering the slider.

This is no real issue to me, so thank you for your work and your help. 👍

**Comment by 1thinkdifferent** [comment]
after the last update of the creators update, i get invalid handler ( that means the drivers are not working properly ), anyone has find a fix yet? 
after the update it tried to reinstall the drivers but it didn't work
