### ISSUE TITLE
Not working after Windows 10 April Update

### ISSUE THREAD

**Issue by mauroraptor86** [jaryn-kubik/AcerFanControl#6]
The error showed reads:

System.Exception: Invalid device handle
in AcerFanControl.AcerFancontrolLib.checkError(FanControlErrorresults)
in AcerFanControl.MainWindows.mainSlider_ValueChanged(Objectsender, RoutedPropetryChangedEventsArgs'1 e)

**Comment by jbehler** [comment]
It's the same on my updated device!

**Comment by mauroraptor86** [comment]
Delete and re-install the drivers worked for me!
