### ISSUE TITLE
Request: Permanently set fan speed

### ISSUE THREAD

**Issue by ArkfrostLumas** [jaryn-kubik/AcerFanControl#7]
Hello,

first of all, I love this software. I have searched for ages, to find anything, to increase fan speed on my Acer Aspire E1-571G and nothing worked. Not SpeedFan, not Notebook Fan Control, not Argus Monitor and in the BIOS I can't do anything either.
But this here works like a charm. Like a real miracle. I set it to on and the fan instantly goes to 100% like crazy.

Now, there is one thing, I'd really like to have, which is an option, to permanently keep fan speed at 100%, instead of it going back down to normal after a set time, because I want to play an MMO on my laptop and because Acer doesn't seem to properly handle the CPU temperature, the laptop simply crashes mid-game frequently due to overheating.

Would this be possible to implement? Either way, this is already awesome and great work!

**Comment by kubik-jaroslav** [comment]
IIRC the way it works is it keeps going at 100% as long as the CPU/GPU temp is above the selected temperature. The interval is there only so it doesn't switch between on/off that often if you're hovering around the selected temp.

The only problem I can imagine is if your laptop can go from 70C to crash under the 30sec delay before it switches back on. I made a new release where you can change the trigger temperature down to 40C and decrease the delay down to 10s, that should allow you to basically set it to on permanently if you want.

I don't have a way to test this, if the app doesn't start try replacing just the exe from the new release while keeping the old dlls..

**Comment by c-schmitz** [comment]
@jaryn-kubik Can you please explain which register you set so it goes to 100%.
I am trying to reproduce.
