### ISSUE TITLE
any chance releasing for linux?

### ISSUE THREAD

**Issue by chxei** [jaryn-kubik/AcerFanControl#8]
Tried several linux distros, each one has fan problems, even on 90c fans aren't working fully, what can i I do?

**Comment by CristianSarac** [comment]
There are some options out there that run on Linux , if you are still looking for a solution

**Comment by chxei** [comment]
> There are some options out there that run on Linux , if you are still looking for a solution

Yes, I'm still looking for solution

**Comment by CristianSarac** [comment]
This is a perl script that was buit a while ago and on which most of linux solutions are based.
[Perl script](https://github.com/neduard/acer_5750G_fan_maximiser)
I have built a UI based on the script [here](https://github.com/CristianSarac/Acer_Fan_Controller)
Also there is this UI too  [here](https://github.com/LeonardKoenig/FanSetQt)
If you need help just let me know

**Comment by chxei** [comment]
> This is a perl script that was buit a while ago and on which most of linux solutions are based.
> [Perl script](https://github.com/neduard/acer_5750G_fan_maximiser)
> I have built a UI based on the script [here](https://github.com/CristianSarac/Acer_Fan_Controller)
> Also there is this UI too [here](https://github.com/LeonardKoenig/FanSetQt)
> If you need help just let me know

Thank you very much sir, it was even easier than on windows :)
